movieapp/movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update' ),
    path('delete/<int:id>/',views.delete,name='delete' ),
]

movieapp/movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieapp/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='piccs')

    def __str__(self):
        return self.name

movieapp/movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','img','year']

movieapp/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie


# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieapp/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<style>
<!--to make all input box same size-->
  input {
    height: 50px;
    width: 200px;
  }
</style>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter name"><br>
  <input type="file" name="img" placeholder="Enter image  "><br>
  <input name="desc" placeholder="Enter description"><br>
  <input type="number" name="year" placeholder="Enter year"><br><br>
  <input type="submit" value="Submit">
</form>
<div style="text-align: left;">
    <a href="{% url 'movieapp:index'  %}" class="btn btn-primary">Back</a>
</div>
{% endblock %}

movieapp/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieapp/movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  Do you want to delete?
  <input type="submit">
</form>
{% endblock %}

movieapp/movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class=" mt-4 col-md-6">
            <img src="{{movie.img.url}}"  width="350" height="500">
        </div>
        <div class=" mt-4 col-md-6">
            <h3>{{movie.name}}</h3>
            <h5>{{movie.desc}}</h5>
            <h5>{{movie.year}}</h5>
            <a class= "btn btn-warning" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
            <a class= "btn btn-success" href="{% url 'movieapp:update' movie.id %}">Update</a>
        </div>
    </div>
</div>

{% endblock %}

movieapp/movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock %}

movieapp/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container" >
    <div class="row">
        {% for i in movie_list %}
        <div class="mt-4 col-md-4 " >
            <div class="card" >
            <img class="card-img-top" src="{{i.img.url}}" alt=" "  height="250">
            <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
            <p class="card-text" >{{i.desc}}</p>
            <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Know more</a>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div style="text-align: center;width: 1700px;height: 160px;padding-top: 60px;">
    <a href="{% url 'movieapp:add_movie'  %}" class="btn btn-primary">Add new</a>
</div>

{% endblock %}